# Generated by Django 4.1.4 on 2022-12-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='full_name',
        ),
    ]
